server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/messenger}

redis:
  url: ${REDIS_URL:redis://localhost:6379}

app:
  jwt:
    secret: ${APP_JWT_SECRET:changemechangemechangeme}

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
